### PR TITLE
Maya 2020 and vs 15 configuration

### PR DESCRIPTION
**Pull request by miquelcampos**
Hello Gaetan,

I did some changes to support Maya 2020 and visual studio 2017  (v15)

here is more info about the dev platform for Maya 2020 https://around-the-corner.typepad.com/adn/2019/12/maya-2020-api-update-guide.html

### CODE REVIEW

**Comment by miquelcampos** [comment]
ops I see some conflicts. My bad. Let me check this. I will create a new pull request. Sorry

**Comment by gatgui** [comment]
Now i noticed it, mscver should actually be 14.1 not 15.0

https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B

Visual studio and Visual C++ runtime version is really misleading...

**Comment by miquelcampos** [comment]
Oh! I see . I had issues and I was thinking that was my VS installation issue :O.

~~I will change it and do another PR~~
EDIT: notice that you already fix it

**Comment by gatgui** [comment]
already changed it, just pull

**Pull request closed without merging**
